### ISSUE TITLE
pyqt5 native

### ISSUE THREAD

**Issue by bchoineubility** [meta-qt5/meta-qt5#544]
Hi,

I failed to build qt-gui-cpp_2.2.2-1.bb in ros.  error message is are : 

```
| cd /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/git/src/qt_gui_cpp_sip && /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot/usr/share/python_qt_binding/cmake/sip_configure.py /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/build/sip/qt_gui_cpp_sip qt_gui_cpp.sip /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/build/src/qt_gui_cpp_sip "/home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/git/src/qt_gui_cpp_sip/../../include /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot/usr/include/pluginlib /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot/usr/include/ament_index_cpp /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot/usr/include/class_loader /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot/usr/include /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot/usr/include/rcpputils /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot/usr/include/rcutils /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot/usr/include/python3.10" "/home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot/usr/lib/libament_index_cpp.so /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot/usr/lib/libconsole_bridge.so.1.0 dl /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot/usr/lib/librcutils.so /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot/usr/lib/librcpputils.so /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot/usr/lib/libclass_loader.so /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot/usr/lib/libtinyxml2.so.9.0.0 /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot/usr/lib/libtinyxml2.so.9.0.0 /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot/usr/lib/libpython3.10.so /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/build/libqt_gui_cpp.so" "lib" ""
| /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot/usr/share/python_qt_binding/cmake/sip_configure.py:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
|   from distutils.spawn import find_executable
| Traceback (most recent call last):
|   File "/home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot/usr/share/python_qt_binding/cmake/sip_configure.py", line 9, in <module>
|     from PyQt5 import QtCore
| ImportError: cannot import name 'QtCore' from 'PyQt5' (unknown location)
| make[2]: *** [src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/build.make:103: sip/qt_gui_cpp_sip/Makefile] Error 1
| make[2]: Leaving directory '/home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/build'
| make[1]: Leaving directory '/home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/build'
| make[1]: *** [CMakeFiles/Makefile2:253: src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/all] Error 2
| make: *** [Makefile:146: all] Error 2
| WARNING: exit code 2 from a shell command.
ERROR: Task (/home/bchoi/work/ros_humble_build/sources/meta-ros/meta-ros2-humble/generated-recipes/qt-gui-core/qt-gui-cpp_2.2.2-1.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2356 tasks of which 2347 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/bchoi/work/ros_humble_build/sources/meta-ros/meta-ros2-humble/generated-recipes/qt-gui-core/qt-gui-cpp_2.2.2-1.bb:do_compile
Summary: There was 1 WARNING message.
Summary: There was 1 ERROR message, returning a non-zero exit code.
```

I think this issue occurred with python3-native do not have pyqt5 module even though pyqt5 is built successfully with python3-pyqt5 recipe.

Actually, when I run with below, it occurred error that does not have pyqt5.

```
bchoi@nvidia-build:~/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/git/src/qt_gui_cpp_sip$ /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
Python 3.10.9 (main, Dec  6 2022, 18:44:57) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5 import QtCore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'QtCore' from 'PyQt5' (unknown location)
>>>
```
My python3-native version is 
```
bchoi@nvidia-build:~/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/git/src/qt_gui_cpp_sip$ /home/bchoi/work/ros_humble_build/bchoi-build/tmp/work/armv8a-poky-linux/qt-gui-cpp/2.2.2-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 --version
Python 3.10.9
```

Can you please let me know how to bind pyqt5 on meta-qt5 to pyhon3-native ?

BR,
Mark

**Comment by robwoolley** [comment]
This pull request should help provide python3-pyqt5-native: https://github.com/meta-qt5/meta-qt5/pull/546
